'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl vygenerován nástrojem.
'
'     Změny v tomto souboru mohou způsobit nesprávné chování a budou ztraceny, pokud
'     bude kód vygenerován znovu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My.Resources

    'Tato třída byla vygenerována automaticky prostřednictvím třídy StronglyTypedResourceBuilder
    'v nástroji jako ResGen či Visual Studio.
    'Chcete-li přidat či odebrat člena, upravte svůj soubor .ResX a poté znovu spusťte nástroj ResGen
    's parametrem /str, nebo znovu sestavte svůj projekt VS.
    '<summary>
    '  Silně typovaná třída prostředků, pro vyhledávání lokalizovaných řetězců apod.
    '</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

        '<summary>
        '  Vrací instanci ResourceManager uloženou v mezipaměti používanou touto třídou.
        '</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("electronic_trading.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '<summary>
        '  Přepisuje vlastnost CurrentUICulture aktuálního vlákna pro všechna
        '  vyhledávání prostředků pomocí této silně typované třídy prostředků.
        '</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property
    End Module
End Namespace
